### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by yeasin90** [PrismLibrary/Prism-Samples-Windows#10]
I was trying to to Build the error. But i got the following build errors : 

> Severity  Code    Description Project File    Line    Suppression State
> Error     The "StyleCopTask" task could not be loaded from the assembly C:\Users\yeasin.nuget\packages\StyleCop.MSBuild\4.7.49.1\build..\tools\StyleCop.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.   AdventureWorks.UILogic

**Comment by bartlannoeye** [comment]
StyleCop is just a NuGet package. Can you try to restore all packages and check if you find a StyleCop.MSBuild folder under $(UserProfile)\.nuget\packages\

**Comment by Robzilla** [comment]
Was also getting this error, the problem was that .net 3.5 was not installed.
