### ISSUE TITLE
Exception on debug in Windows 10 Build 14986

### ISSUE THREAD

**Issue by TheOriginalAppStar** [PrismLibrary/Prism-Samples-Windows#15]
I'm getting an exception when I try to debug the sample apps in Visual Studio with Windows 10 Insider Build 14986.
"0xC0000005 occurred
Exception thrown at 0x0FCEA592 (Windows.UI.Xaml.dll) in SplitViewSample.exe: 0xC0000005: Access violation reading location 0x00000000."

Is my build not supported?

**Comment by brianlagunas** [comment]
I am assuming this works on the RTM build of Windows 10 :)
