### ISSUE TITLE
NavigationService.NavigateAsync Absolute doesn't prevent viewing previos pages on stack

### ISSUE THREAD

**Issue by ederbond** [PrismLibrary/Prism-Samples-Windows#16]
Steps to reproduce:
1 - Create a Prism.<Container>.Forms app
2 - Add a "LoginPage"
3 - Add a  "LoginViewModel" 
On LoginPageViewModel add this command:
```
public class LoginPageViewModel : ViewModelBase
    {
        public LoginPageViewModel(INavigationService navigationService)
        {
            NavigationService = navigationService;
        }

        private string userName;

        public string UserName
        {
            get { return userName; }
            set { SetProperty(ref userName, value); }
        }

        private string password;

        public string Password
        {
            get { return password; }
            set { SetProperty(ref password, value); }
        }

        public DelegateCommand LoginCommand => new DelegateCommand(Login, CanLogin).ObservesProperty(() => UserName)
                                                                                   .ObservesProperty(() => Password);

        private bool CanLogin()
        {
            return !(string.IsNullOrWhiteSpace(UserName) || string.IsNullOrWhiteSpace(Password));
        }

        private async void Login()
        {
            await NavigationService.NavigateAsync(new Uri("http://test.com/"+Pages.MainPage, UriKind.Absolute));
        }
    }
```

4 - Add a "MainPage" and its related ViewModel

5 - Set LoginPage as the startup page;

6 - Run the application on android;
Hit the button on LoginPage to navigate to MainPage;

7 - Press the back button on Android

8 - The app will "close"

9 - Open the "task manager / mutitask window" of Android a select you app;

10 - It will resume the app on the login page againd, witch is wrong because after navigating absolute from LoginPage to MainPage, the xamarin.forms navigation stack was supposed to be reseted and the user was supposed to see the LoginPage again; I was expecting the app to be definetly closed after step 7

**Comment by brianlagunas** [comment]
When using an absoluteUri, Prism simply set the `MainPage = new SomePage()`.  Prism has no control over this behavior.  This is a Xamarin.Forms bug, or it could be by design.  I bet you can easily duplicate this behavior without using Prism.  I would submit this to Xamarin.

**Comment by ederbond** [comment]
I'm using this version of libs:

```
<package id="Prism.Core" version="6.2.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Prism.DryIoc.Forms" version="6.2.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Prism.Forms" version="6.2.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
<package id="Xamarin.Forms" version="2.3.1.114" targetFramework="portable45-net45+win8+wp8+wpa81" />
```

**Comment by brianlagunas** [comment]
I just tested this using only XF with no Prism, and it behaved the same way.  This is a Xamarin bug.  Please report this to them.

**Comment by ederbond** [comment]
Ok. Thanks Braian.

**Comment by therealjohn** [comment]
For additional context on _why_ this happens in Xamarin.Forms, consider [this](https://bugzilla.xamarin.com/show_bug.cgi?id=29275) issue. It's working as designed right now.
