### ISSUE TITLE
Splash screen wrong position on a mobile device in ExtendedSplashScreenDemo

### ISSUE THREAD

**Issue by artemious7** [PrismLibrary/Prism-Samples-Windows#17]
The splash screen has wrong position on a mobile device (Windows 10 Mobile) in ExtendedSplashScreenDemo (at least in portrait mode). 
Looks like, it's because of the Assets/SplashScreen.png picture size - it is landscape instead of portrait.
Still, the OS knows how to display this same image for splash screen when starting the app, but ExtendedSplashScreenDemo can't propertly position this image.
Please, explain, how to fix this. 

![wp_ss_20170206_0001](https://cloud.githubusercontent.com/assets/16724889/22684285/66c23796-ed24-11e6-97a2-f93ecf5b019c.png)

**Comment by brianlagunas** [comment]
@bartlannoeye do you know what the issue here is?
