### ISSUE TITLE
Please update samples

### ISSUE THREAD

**Issue by ericwj** [PrismLibrary/Prism-Samples-Windows#19]
I'm seeing you're making a website [Prism#411](/PrismLibrary/Prism/issues/411) and possibly docs - another thing I'd like to see is up to date samples.

* For starters, the projects are set to `<TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>` which is ancient by now.
* They use Newtonsoft.Json 7, Uwp 5.0.0 and Prism 6.1.1
* The project files are using packages.config which is pure evil given that you can now do without.
* StyleCop is broken on my system - I have to edit the project file to make the project build at all. Why would a sample have StyleCop at all? 
* The AdventureWorks sample uses an extension method `FromAsyncHandler` to make a `DelegateCommand` with a Task returning method as execute action, but this extension method was obsoleted and removed since.

I'd be happy to hand you the changes I made to fix the above, but I'm just learning Prism, so any changes at the *changed guidance* level could be missing or mis-implemented. And I probably broke something converting all commands to execute **async void** to make the compiler happy.

**Comment by brianlagunas** [comment]
keeping all samples for all platforms updated is a moving target and not the best use of my time.  It is best that when you run into these issues, you update them and provide a PR with the fix :)

**Comment by ericwj** [comment]
OK, well, can you comment on how I fixed these issues? I'm not a Prism Pro. I just made the compiler happy. If there are any changes to the guidance from version 6.1.1 to 6.3, I'd really like someone to have a look and point me to how you'd want me to make other updates.

As far as I can tell, the samples are very useful as they document Prism usage. Especially while the documentation is sparse.

**Comment by brianlagunas** [comment]
Submit your PR.  Then your changes are reviewed and discussed if necessary.  I would suggest making one PR per change as to keep the PR more manageable and more likely to be accepted.  Samples should be in their own repo, and not placed inside the source code repo.  This is how it should always be done.
