### ISSUE TITLE
OnNavigationStateChanged not firing

### ISSUE THREAD

**Issue by Robzilla** [PrismLibrary/Prism-Samples-Windows#21]
Hi all

Created a demo with 7 screens using the same pattern as the sample app and the same Prism NuGet version. But the OnNavigationStateChanged method in the MenuViewModel class never fires. What causes this event to fire? Does overriding the OnNavigatedTo in a real ViewModel kill this behaviour? I made sure to call base.OnNavigatedTo at the top of the override.

**Comment by Robzilla** [comment]
Ok found the problem. Was registering my own instance of IEventAggregator in the App.xaml.cs class (see code snippet below). Once this was commented out the events started firing as per the example.

Container.RegisterInstance<IEventAggregator>(new EventAggregator());

**Comment by brianlagunas** [comment]
Glad you figured it out
