### ISSUE TITLE
Weird Sizing Behavior

### ISSUE THREAD

**Issue by mike-ward** [PrismLibrary/Prism-Samples-Windows#22]
Cloned and built. When I size the window with the mouse the app contents and title bar display some weird behavior as illustrated.

![prism-app](https://user-images.githubusercontent.com/567927/27565072-c9b7ed58-5aa9-11e7-8b50-95ca917db611.gif)

I'm seeing this in my own apps as well.

**Comment by mike-ward** [comment]
I built the same stuff on a different computer today and everything works correctly. Both running the same version of Windows 10.

**Comment by brianlagunas** [comment]
While this is a strange behavior, this has nothing to do with Prism.  It is even stranger how it works on one machine and not another.  Fun times being a dev :)
