### ISSUE TITLE
Didn't found any sample up to date to the last version of prism

### ISSUE THREAD

**Issue by dust63** [PrismLibrary/Prism-Samples-Windows#25]
Hi,

I'm trying to code an UWP app with the last Prism Windows package. 

- Prism.Unity 7.2.0.1367
- Prism.Windows 6.3.0

The given sample is not up to date to the last version. 
For example I didn't found the PrismUnityApplication class in the new version.

Regards.

**Comment by brianlagunas** [comment]
There is no Prism.Windows anymore.
