### ISSUE TITLE
ExtendedSplashScreen using PrismLibrary is not working

### ISSUE THREAD

**Issue by tjones0808** [PrismLibrary/Prism-Samples-Windows#5]
I have implemented the extendedsplash screen but it seems to crash on load every time. 

I am getting exception: {"Value cannot be null.\r\nParameter name: key"}

StackTrace:    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Prism.Windows.Mvvm.SessionStateAwarePage.OnNavigatedFrom(NavigationEventArgs e)
   at ILG.Views.ExtendedSplashScreen.OnNavigatedFrom(NavigationEventArgs e)

I have already tried to implement the base calls on the overrides for my screens.. nothing is working. 

ExtendedSplashScreen.xaml.cs:

   public sealed partial class ExtendedSplashScreen : SessionStateAwarePage
    {
        private readonly SplashScreen _splashScreen;
        internal bool dismissed = false;
        public ExtendedSplashScreen(SplashScreen splashScreen)
        {
            this._splashScreen = splashScreen;

            this.InitializeComponent();

            this.SizeChanged += ExtendedSplashScreen_SizeChanged;
            this.splashImage.ImageOpened += SplashImage_ImageOpened;
            
        }

        protected override void OnNavigatedFrom(NavigationEventArgs e)
        {
            base.OnNavigatedFrom(e);
        }

        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
        }

        private void SplashImage_ImageOpened(object sender, RoutedEventArgs e)
        {
            Resize();
            Window.Current.Activate();
        }

        private void ExtendedSplashScreen_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            this.Resize();
        }

        private void Resize()
        {
            if (this._splashScreen == null) return;

            // The splash image's not always perfectly centered. Therefore we need to set our image's position 
            // to match the original one to obtain a clean transition between both splash screens.

            this.splashImage.Height = this._splashScreen.ImageLocation.Height;
            this.splashImage.Width = this._splashScreen.ImageLocation.Width;

            this.splashImage.SetValue(Canvas.TopProperty, this._splashScreen.ImageLocation.Top);
            this.splashImage.SetValue(Canvas.LeftProperty, this._splashScreen.ImageLocation.Left);

            this.progressRing.SetValue(Canvas.TopProperty, this._splashScreen.ImageLocation.Top + this._splashScreen.ImageLocation.Height + 50);
            this.progressRing.SetValue(Canvas.LeftProperty, this._splashScreen.ImageLocation.Left + this._splashScreen.ImageLocation.Width / 2 - this.progressRing.Width / 2);
        }
    }

**Comment by brianlagunas** [comment]
Why are you deriving from SessionStateAwarePage?

**Comment by brianlagunas** [comment]
Either change your base class to Page, or just remove the calls to base.OnNavigatedTo/From and let me know if that works for you.

This Extended Splash Screen sample in our samples repos works without issue.

https://github.com/PrismLibrary/Prism-Samples-Windows/tree/master/ExtendedSplashScreenDemo/ExtendedSplashScreenDemo

**Comment by tjones0808** [comment]
good question... i just started working with the UWP framework and unity/prism.. was adding that to all my new pages... reverted to a simple page and it's working now

**Comment by tjones0808** [comment]
gracias

**Comment by brianlagunas** [comment]
sweet!  Glad it was a simple fix.
