### ISSUE TITLE
Can't override OnLaunchApplicationAsync

### ISSUE THREAD

**Issue by Brian-Ding** [PrismLibrary/Prism-Samples-Windows#6]
![image](https://cloud.githubusercontent.com/assets/11363173/14065858/8ed4e5e6-f46c-11e5-95b3-9f8203c3831d.png)

any ideas? plz help

**Comment by bartlannoeye** [comment]
Just double checking that you're working on a Windows 10 UWP app and got the lastest Prism.Unity package (try 6.2.0-pre3)? I created a new app and was able to build this code without a problem:

    sealed partial class App : PrismUnityApplication
    {
        /// <summary>
        /// Initializes the singleton application object.  This is the first line of authored code
        /// executed, and as such is the logical equivalent of main() or WinMain().
        /// </summary>
        public App()
        {
            this.InitializeComponent();
        }

        protected override Task OnLaunchApplicationAsync(LaunchActivatedEventArgs args)
        {
            // tadaaa
            return Task.CompletedTask;
        }
    }
