### ISSUE TITLE
Bulid error CS0534 OnLaunchApplicationAsync not implemented in App.xaml.cs

### ISSUE THREAD

**Issue by AlexanderViken** [PrismLibrary/Prism-Samples-Windows#9]
I am trying to build the sample app using Visual Studio 2015 Update 2 but it fails with this error: 

Error CS0534	'App' does not implement inherited abstract member 'PrismApplication.OnLaunchApplicationAsync(LaunchActivatedEventArgs)'

When i comment out the existing override of OnLaunchApplicationAsync and try to recreate it with auto complete the method throws a NotImplementedException instead of returning base.OnLaunchApplicationAsync(args)

**Comment by bartlannoeye** [comment]
I had to rebuild the Shopper solution locally to get rid of the errors, but all 3 solutions build fine under Update 1. I'm repaving my other pc next weekend and will put Update 2 on it to double check.

**Comment by AlexanderViken** [comment]
This issue was caused by myself, having a typo error in the x:Class in App.xaml
